backend:
  name: git-gateway
  repo: RedCiudadana/ForoTransformacionDigital
  branch: main
  identity_url: https://auth.decapbridge.com/sites/d0132826-04f9-4ab8-bb6f-e2a89d01fd92
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "leyes"
    label: "Leyes"
    folder: "src/content/leyes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción corta", name: "shortDescription", widget: "string" }
      - { label: "Descripción completa", name: "fullDescription", widget: "markdown" }
      - label: "Icono"
        name: "icon"
        widget: "select"
        options:
          - { label: "Escudo", value: "shield" }
          - { label: "Huella", value: "fingerprint" }
          - { label: "Red", value: "network" }
      - label: "Color"
        name: "color"
        widget: "select"
        options:
          - { label: "Azul", value: "blue" }
          - { label: "Verde", value: "green" }
          - { label: "Morado", value: "purple" }
      - { label: "URL del PDF", name: "pdfUrl", widget: "string" }
      - label: "Artículos"
        name: "articles"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Número", name: "number", widget: "string" }
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "content", widget: "markdown" }
