/*
  # Seed document sections

  Populates the `sections` JSONB field on each published document with
  structured paragraphs drawn from the K'atun 2032 plan content.
  Each section has: id (text slug), title, and content (paragraph text).
*/

UPDATE documents
SET sections = '[
  {"id":"vision","title":"Visión del Plan","content":"K''atun: Nuestra Guatemala 2032 es el Plan Nacional de Desarrollo de Guatemala, aprobado por el Consejo Nacional de Desarrollo Urbano y Rural (CONADUR) en 2014. Establece la visión estratégica del país al año 2032, articulando prioridades nacionales en torno a cinco dimensiones del desarrollo."},
  {"id":"marco","title":"Marco Estratégico","content":"El Plan surge de un amplio proceso de consulta y diálogo con distintos actores del desarrollo: comunidades, organizaciones sociales, sector privado, academia, pueblos indígenas, juventudes, mujeres y gobiernos locales. Su construcción participativa le otorga legitimidad y representatividad como hoja de ruta compartida."},
  {"id":"dimensiones","title":"Las Cinco Dimensiones","content":"El K''atun 2032 estructura sus prioridades en cinco dimensiones interrelacionadas: (1) Bienestar para la Gente, (2) Riqueza para Todos y Todas, (3) Recursos Naturales para Hoy y para el Futuro, (4) Guatemala Urbana y Rural, y (5) Estado como Garante de los Derechos Humanos y Conductor del Desarrollo."},
  {"id":"implementacion","title":"Implementación y Seguimiento","content":"La implementación del Plan requiere la articulación de políticas públicas, planes sectoriales e inversión pública con los objetivos y metas del K''atun 2032. SEGEPLAN coordina el monitoreo y evaluación del avance, reportando periódicamente al CONADUR sobre el cumplimiento de los compromisos establecidos."},
  {"id":"actualizacion","title":"Proceso de Actualización","content":"Guatemala inicia en 2025 el proceso de actualización del Plan Nacional de Desarrollo K''atun 2032, incorporando los aprendizajes de la implementación, los cambios en el contexto nacional e internacional, y las nuevas prioridades identificadas en procesos participativos. Este ejercicio busca fortalecer la relevancia y pertinencia del Plan como instrumento rector del desarrollo nacional."}
]'::jsonb
WHERE id = '48cb4b6b-4f1a-4129-897e-52fd8626ca0a';

UPDATE documents
SET sections = '[
  {"id":"objetivo","title":"Objetivo de la Dimensión","content":"La dimensión de Bienestar para la Gente busca garantizar condiciones de vida dignas para toda la población guatemalteca, con énfasis en los grupos en situación de mayor vulnerabilidad. Aborda el acceso a servicios públicos de calidad, la protección social y el ejercicio pleno de los derechos económicos y sociales."},
  {"id":"salud","title":"Salud y Nutrición","content":"Guatemala enfrenta una carga persistente de desnutrición crónica infantil, especialmente en comunidades rurales e indígenas. El K''atun 2032 plantea fortalecer el primer nivel de atención en salud, ampliar la cobertura de servicios de salud materna e infantil, y articular intervenciones de seguridad alimentaria y nutricional con enfoque territorial."},
  {"id":"educacion","title":"Educación de Calidad","content":"El acceso a una educación pertinente, de calidad y con pertinencia cultural es fundamental para el desarrollo humano. La dimensión impulsa la ampliación de cobertura en educación preprimaria y secundaria, la reducción del fracaso escolar y el rezago educativo, y la mejora de los aprendizajes con atención a la diversidad lingüística y cultural del país."},
  {"id":"proteccion","title":"Protección Social","content":"Se busca consolidar un sistema nacional de protección social que brinde cobertura frente a riesgos como la pobreza, la enfermedad, la discapacidad y la vejez. Las intervenciones contemplan transferencias condicionadas, programas de generación de ingresos y mecanismos de aseguramiento para poblaciones sin acceso al sistema contributivo."},
  {"id":"metas","title":"Metas al 2032","content":"Entre las metas centrales de la dimensión se incluyen: reducir la desnutrición crónica infantil a menos del 30%, aumentar la tasa de finalización del ciclo básico al 60%, y ampliar la cobertura de protección social al 40% de la población en situación de pobreza extrema. Estas metas requieren incrementos sostenidos en la inversión social y mejoras en la eficiencia del gasto público."}
]'::jsonb
WHERE id = 'c8a6c67d-3315-44a2-9551-50bd227d05c2';

UPDATE documents
SET sections = '[
  {"id":"objetivo","title":"Objetivo de la Dimensión","content":"La dimensión Riqueza para Todos y Todas busca transformar la estructura productiva del país para generar crecimiento económico inclusivo, crear empleos dignos y reducir las brechas de desigualdad. Reconoce que el desarrollo económico sostenible requiere condiciones habilitantes como infraestructura, capital humano, acceso a financiamiento y un entorno de negocios que promueva la competitividad."},
  {"id":"empleo","title":"Empleo Digno y Productivo","content":"Guatemala necesita generar anualmente más de 200,000 empleos formales para absorber a los jóvenes que se incorporan al mercado laboral. El K''atun 2032 apuesta por el fortalecimiento de sectores con alto potencial de generación de empleo: agroindustria, turismo, manufactura y economía digital, con énfasis en la formalización laboral y el respeto a los derechos de los trabajadores."},
  {"id":"mipymes","title":"Micro, Pequeñas y Medianas Empresas","content":"Las MIPyMEs representan más del 80% del tejido empresarial guatemalteco y son fuente fundamental de empleo, especialmente en el ámbito rural. La dimensión promueve el acceso a financiamiento, asistencia técnica, mercados y tecnología para estas empresas, con especial atención a emprendimientos liderados por mujeres y jóvenes."},
  {"id":"infraestructura","title":"Infraestructura Productiva","content":"La inversión en infraestructura vial, energética, de telecomunicaciones y de riego es condición necesaria para la competitividad territorial y la integración de las cadenas productivas. El Plan prioriza la rehabilitación y ampliación de la red vial, la universalización del acceso a energía eléctrica y la conectividad digital en zonas rurales."},
  {"id":"metas","title":"Metas al 2032","content":"Las metas de la dimensión incluyen: reducir la informalidad laboral al 55%, aumentar la contribución del sector manufacturero al PIB en 5 puntos porcentuales, y duplicar las exportaciones de bienes y servicios con valor agregado. El logro de estas metas requiere políticas macroeconómicas estables, inversión sostenida en capital humano y reformas al clima de negocios."}
]'::jsonb
WHERE id = '5c030a29-2021-4292-a12e-571fa812f6dc';

UPDATE documents
SET sections = '[
  {"id":"objetivo","title":"Objetivo de la Dimensión","content":"La dimensión Recursos Naturales para Hoy y para el Futuro reconoce que Guatemala es un país megadiverso con una riqueza natural extraordinaria que constituye la base del bienestar presente y futuro de su población. Su objetivo es promover la gestión sostenible del patrimonio natural, la adaptación al cambio climático y la reducción del riesgo a desastres."},
  {"id":"biodiversidad","title":"Biodiversidad y Ecosistemas","content":"Guatemala alberga una notable biodiversidad en sus catorce ecorregiones, incluyendo selvas tropicales, bosques nubosos, humedales y arrecifes de coral. El Plan plantea consolidar el Sistema Guatemalteco de Áreas Protegidas, fortalecer la gestión comunitaria de los recursos naturales y reducir la deforestación mediante incentivos forestales y el ordenamiento del uso del suelo."},
  {"id":"agua","title":"Gestión del Recurso Hídrico","content":"El agua es un recurso estratégico para el desarrollo de Guatemala, esencial para la producción agrícola, el consumo humano y la generación de energía. La dimensión impulsa la gobernanza integrada del recurso hídrico, la protección de fuentes de agua, el tratamiento de aguas residuales y la ampliación de sistemas de riego eficientes para la producción alimentaria."},
  {"id":"clima","title":"Cambio Climático y Riesgo","content":"Guatemala es uno de los países más vulnerables al cambio climático en América Latina. El K''atun 2032 integra la gestión del riesgo a desastres y la adaptación climática como ejes transversales del desarrollo, promoviendo la reducción de la vulnerabilidad territorial, el fortalecimiento de sistemas de alerta temprana y la transición hacia una economía baja en carbono."},
  {"id":"metas","title":"Metas al 2032","content":"Las metas de la dimensión contemplan: reducir la tasa de deforestación neta a cero, aumentar la cobertura forestal al 38% del territorio nacional, y garantizar acceso a agua potable al 95% de los hogares. Estas metas requieren aumentos significativos en la inversión ambiental y reformas institucionales para la gobernanza de los recursos naturales."}
]'::jsonb
WHERE id = '5f4e2640-2cfd-4d5a-a1f7-03660263f885';

UPDATE documents
SET sections = '[
  {"id":"objetivo","title":"Objetivo de la Dimensión","content":"La dimensión Guatemala Urbana y Rural aborda los desafíos del desarrollo territorial, reconociendo la diversidad de los contextos urbanos, rurales e intermedios del país. Busca reducir las brechas de desarrollo entre territorios, mejorar la calidad de vida en las ciudades y fortalecer las economías locales rurales con un enfoque de ordenamiento territorial."},
  {"id":"urbano","title":"Desarrollo Urbano Sostenible","content":"Guatemala Ciudad y las ciudades intermedias enfrentan presiones crecientes por el crecimiento demográfico acelerado, la expansión urbana no planificada y el deterioro de la infraestructura básica. El Plan promueve la planificación urbana participativa, la movilidad sostenible, el mejoramiento de asentamientos precarios y la gestión eficiente de los servicios públicos municipales."},
  {"id":"rural","title":"Desarrollo Rural Integral","content":"Las áreas rurales de Guatemala concentran los mayores índices de pobreza y exclusión social. La dimensión impulsa el desarrollo rural integral mediante el fortalecimiento de las economías campesinas, el acceso a la tierra, la diversificación productiva, la provisión de servicios básicos y la conectividad vial y digital que articule los territorios rurales con los mercados."},
  {"id":"vivienda","title":"Acceso a Vivienda Digna","content":"El déficit habitacional en Guatemala supera el millón y medio de unidades, afectando principalmente a hogares de bajos ingresos en áreas urbanas marginales y zonas rurales. El K''atun 2032 plantea ampliar el acceso a soluciones habitacionales asequibles mediante subsidios focalizados, crédito hipotecario accesible y programas de mejoramiento de vivienda existente."},
  {"id":"metas","title":"Metas al 2032","content":"Entre las metas de la dimensión se encuentran: reducir el déficit habitacional cualitativo en un 40%, garantizar acceso a saneamiento al 85% de los hogares, y aumentar la inversión municipal en infraestructura al 3% del PIB. El logro de estas metas requiere el fortalecimiento de las capacidades de los gobiernos locales y la descentralización efectiva de recursos y competencias."}
]'::jsonb
WHERE id = 'd5a27586-4ffe-42ca-9dd4-c79391512d2f';

UPDATE documents
SET sections = '[
  {"id":"objetivo","title":"Objetivo de la Dimensión","content":"La dimensión Estado como Garante de los Derechos Humanos y Conductor del Desarrollo reconoce que un Estado fuerte, democrático, transparente y eficiente es condición indispensable para el desarrollo sostenible. Busca fortalecer las instituciones públicas, combatir la corrupción, ampliar el acceso a la justicia y profundizar la democracia participativa."},
  {"id":"institucionalidad","title":"Fortalecimiento Institucional","content":"Guatemala requiere una profunda reforma del Estado para mejorar la calidad y eficiencia de los servicios públicos, reducir la corrupción e impunidad, y restablecer la confianza ciudadana en las instituciones. El K''atun 2032 impulsa la profesionalización del servicio civil, la modernización de los sistemas de gestión pública y el fortalecimiento de los órganos de control y fiscalización."},
  {"id":"justicia","title":"Acceso a la Justicia","content":"El acceso equitativo a la justicia es un derecho fundamental y condición para la cohesión social. La dimensión promueve la reforma del sistema de justicia para hacerlo más accesible, ágil y transparente, con especial atención a la justicia en el ámbito rural, la protección de los derechos de las mujeres y pueblos indígenas, y la lucha contra la impunidad."},
  {"id":"participacion","title":"Participación y Democracia","content":"La profundización de la democracia requiere fortalecer los mecanismos de participación ciudadana en las decisiones públicas. El Plan promueve el funcionamiento efectivo del Sistema de Consejos de Desarrollo, la transparencia en la gestión pública mediante acceso a la información, y el fortalecimiento de los partidos políticos como articuladores de la representación democrática."},
  {"id":"metas","title":"Metas al 2032","content":"Las metas de la dimensión incluyen: reducir la percepción de corrupción en el sector público al nivel promedio de América Latina, aumentar la recaudación tributaria al 15% del PIB, y garantizar resolución judicial oportuna al 70% de los casos ingresados al sistema. Estas metas requieren reformas estructurales profundas y sostenidas en el tiempo, más allá de los ciclos electorales."}
]'::jsonb
WHERE id = '90205e7e-26d1-400f-a1d7-63e91f7789c2';
